// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Legivel.Mapper")>]
[<assembly: AssemblyProductAttribute("Legivel")>]
[<assembly: AssemblyDescriptionAttribute("F# Yaml deserializer")>]
[<assembly: AssemblyVersionAttribute("0.4.3")>]
[<assembly: AssemblyFileVersionAttribute("0.4.3")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Legivel.Mapper"
    let [<Literal>] AssemblyProduct = "Legivel"
    let [<Literal>] AssemblyDescription = "F# Yaml deserializer"
    let [<Literal>] AssemblyVersion = "0.4.3"
    let [<Literal>] AssemblyFileVersion = "0.4.3"
    let [<Literal>] AssemblyConfiguration = "Release"
