// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Legivel.Mapper")>]
[<assembly: AssemblyProductAttribute("Legivel")>]
[<assembly: AssemblyDescriptionAttribute("F# Yaml deserializer")>]
[<assembly: AssemblyVersionAttribute("0.4.6")>]
[<assembly: AssemblyFileVersionAttribute("0.4.6")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: AssemblyKeyFileAttribute("c:\Users\Gebruiker\Desktop\ProjectData\Projecten\LegivelMaster/src/Legivel.Signing/Legivel.snk")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Legivel.Mapper"
    let [<Literal>] AssemblyProduct = "Legivel"
    let [<Literal>] AssemblyDescription = "F# Yaml deserializer"
    let [<Literal>] AssemblyVersion = "0.4.6"
    let [<Literal>] AssemblyFileVersion = "0.4.6"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] AssemblyKeyFile = "c:\Users\Gebruiker\Desktop\ProjectData\Projecten\LegivelMaster/src/Legivel.Signing/Legivel.snk"
