// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("YamlParser")>]
[<assembly: AssemblyProductAttribute("YamlParser")>]
[<assembly: AssemblyDescriptionAttribute("F# Yaml deserializer")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("YamlParser.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "YamlParser"
    let [<Literal>] AssemblyProduct = "YamlParser"
    let [<Literal>] AssemblyDescription = "F# Yaml deserializer"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "YamlParser.Tests"
