// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FsYamlParser")>]
[<assembly: AssemblyProductAttribute("FsYamlParser")>]
[<assembly: AssemblyDescriptionAttribute("F# Yaml deserializer")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("FsYamlParser.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsYamlParser"
    let [<Literal>] AssemblyProduct = "FsYamlParser"
    let [<Literal>] AssemblyDescription = "F# Yaml deserializer"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "FsYamlParser.Tests"
