// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Legivel.Tokenizer")>]
[<assembly: AssemblyProductAttribute("Legivel")>]
[<assembly: AssemblyDescriptionAttribute("F# Yaml deserializer")>]
[<assembly: AssemblyVersionAttribute("0.2.1")>]
[<assembly: AssemblyFileVersionAttribute("0.2.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Legivel.Tests")>]
[<assembly: InternalsVisibleToAttribute("Legivel.Mapper")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Legivel.Tokenizer"
    let [<Literal>] AssemblyProduct = "Legivel"
    let [<Literal>] AssemblyDescription = "F# Yaml deserializer"
    let [<Literal>] AssemblyVersion = "0.2.1"
    let [<Literal>] AssemblyFileVersion = "0.2.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Legivel.Tests"
    let [<Literal>] InternalsVisibleTo_1 = "Legivel.Mapper"
