// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Legivel.RepresentationGraph")>]
[<assembly: AssemblyProductAttribute("Legivel")>]
[<assembly: AssemblyDescriptionAttribute("F# Yaml deserializer")>]
[<assembly: AssemblyVersionAttribute("0.3.0")>]
[<assembly: AssemblyFileVersionAttribute("0.3.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Legivel.RepresentationGraph"
    let [<Literal>] AssemblyProduct = "Legivel"
    let [<Literal>] AssemblyDescription = "F# Yaml deserializer"
    let [<Literal>] AssemblyVersion = "0.3.0"
    let [<Literal>] AssemblyFileVersion = "0.3.0"
    let [<Literal>] AssemblyConfiguration = "Release"
